### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by haskellcamargo** [thalesmello/devlindo.vim#1]
Well, I run `devlindo`, but instead of getting better, I'm getting each time more and more tired. I believe it is a bug.

**Comment by filipedeschamps** [comment]
:(

**Comment by thalesmello** [comment]
@haskellcamargo The reason so is because you are typing it incorrectly, as [user defined commands have to be capitalized](https://github.com/vim/vim/blob/bb76f24af2010943387ce696a7092175b4ecccf2/runtime/doc/map.txt#L1145).

If you type the command `devlindo`, you actually get the following error message, which you make any person unhappy and tired.

![image](https://cloud.githubusercontent.com/assets/1127394/18522930/7b64c074-7a88-11e6-9796-5fcedb8dcf58.png)

The correct command would be capitalized: `Devlindo`.

![image](https://cloud.githubusercontent.com/assets/1127394/18523000/af3e41cc-7a88-11e6-9ef0-f706cd36d3d9.png)

**Comment by haskellcamargo** [comment]
I'm still sad and tired. :cry:

**Comment by thalesmello** [comment]
@haskellcamargo [This](https://www.youtube.com/channel/UCU5JicSrEM5A63jkJ2QvGYw) might help you.

**Comment by joaolucasl** [comment]
I get sad.
